CREATE TABLE Screenshot_2025_04_14_011548 (
  SUNDAY TEXT,
  MONDAY TEXT,
  TUESDAY TEXT,
  WEDNESDAY TEXT,
  THURSDAY TEXT,
  FRIDAY TEXT,
  SATURDAY TEXT
);
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('RAVA DOSA,UPMA', 'PONGAL , Vada[2]', 'IDLI,RICE BONDA', 'Poori', 'WHEAT RAVA UPMA,POHA,', 'IDLY,VADA (2)', 'ALOO PARATHA');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SAMBAR, C CHUTNEY', 'SAMBAR, G CHUTNEY', 'SAMBAR,C CHUTNEY', 'ALOO CHANNA MASALA', 'MYSORE BONDA3), P CHUTNEY.', 'SAMBAR,G CHUINEY', 'CHANNA MASALA, RAITHA, PICKLE');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('BBJ, SPROUTS*', 'BBJ, SPROUTS*', 'BEJ, SPROUTS*', 'BBJ, SPROUTS*', 'BEJ, SPROUTS*', 'BBJ,SPROUTS*', 'BEJ, SPROUTS*');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SEASONAL CUT FRUITS*', 'BANANA (1)', 'FRUIT***', 'BANANA (1)', 'FRUIT***', 'Banana(1)', 'FRUIT***');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PULKHA , DAL MAKHANI', 'TAWA CHAPATHI, DUM ALOO', 'PULKHA , PANCHRATAN DAL', 'TAWA CHAPATHI , CHANNA MASALA', 'PULKHA ,RAJMA DAL', 'TAWA CHAPATHI, GREEN PEAS KURMA', 'None');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PANEER BUTTER MASALA / KAJU CURRYS', 'RRA INIHE', 'BEANS CARROT PORIYAL', 'ONION PAKODA**, PERUGU PACHADI', 'KADAI PANNER', 'JEERA RICE, BEETROOT PORIYAL', 'LAUKI CHANA DAL, GOBI 65***');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('VEG BIRYANI , ONION RAITHA,Tawa chapatti', 'RICE,SAMBAR,RASAM, CURD', 'CURD,FRYUMS', 'RICE,VATHAKOLAMBU, RASAM,MASALA PAPADS', 'RICE,MASALA SAMBAR, CURD,FRYUMSE', 'RICE,RASAM, CURD,PAPAD', 'RICE, RASAM, CURD,FRYUMS');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('BADUSHA', 'Gongura PICKLE ,PAPAD', 'Mix veg PICKLE', 'Tomato PICKLE', 'Mango PICKLE', 'Lime PICKLE', 'None');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('LEMON JUICE', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR,SALT,GHEE,PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR SALT ,GHEE,PODI');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SALAD', 'MUSKMELON JUICE', 'SALAD', 'BANANA JUICE', 'SALAD', 'SEASONAL FRUIT JUICE', 'None');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PANI PURI', 'PASTA', 'Aloo Bonda,SAUCE', 'BOILED GROUNDNUTS', 'SWEET CORN (half piece-6cm)', 'ONION PAKODA', 'MILLET SNACK**');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('TEA,COFEE,MILK,SUGAR', 'TEA,COFEE,MILK,SUGAR', 'TEA, COFEE,MILK,SUGAR', 'TEA,COFEE,MILK,SUGAR', 'TEA,COFEE,MILK,SUGAR', 'TEA, COFEE,MILK, SUGAR', 'TEA, COFEE,MILK,SUGAR');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('CHAPATTI , ALOO MATTAR', 'CHOLE BATURE, ONION MIRCH SALAD', 'KAL DOSA,TOMATO CHUTNEY', 'PHULKA,VEG BIRYANI, RAITHA', 'LACHA PARATHA ,SALNA', 'PHULKA ,Veg Pulao, RAITHA', 'PULKA,Chitinad Paneer');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('Tamarind Rice, BUTTERMILK,FRYUMS', 'RICE,SAMBAR', 'PANEER MANCHURIAN/gobi MANCHURIANE', 'VEG PORIYAL, RICE, RASAM', 'KAJU CURRY', 'JAGARA RICE, BUTTERMILK', 'None');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('Lime PICKLE,GHEE', 'BUTTER MILK,RASAM', 'PAPAD, BUTTERMILK', 'DAL FRY', 'ONION SALAD', 'Ke sariBath,RASAM', 'VERMICELLI PAYASAM');
INSERT INTO Screenshot_2025_04_14_011548 (SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SEASONAL CUT FRUITS', 'BANANA', 'GULAB JAMUN(2)', 'KHEER', 'BADAM MILK HOT', 'None', 'None');
