CREATE TABLE Screenshot_2025_04_14_010739 (
  SUNDAY TEXT,
  MONDAY TEXT,
  TUESDAY TEXT,
  WEDN_ESDAY TEXT,
  THURSDAY TEXT,
  FRIDAY TEXT,
  SATURDAY TEXT
);
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('RAVA DOSA, UPMA', 'PONGAL , Vada[2)', 'IDLI , RICE BONDA', 'Poari', 'WHEAT RAVA UPMA,POHA,', 'IDLY,VADA (2)', 'ALOO PARATHA');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SAMBAR, C CHUTNEY', 'SAMBAR, G CHUTNEY', 'SAMBAR,C CHUTNEY', 'ALOO CHANNA MASALA', 'MYSORE BONDA(3), P CHUTNEY,', 'SAMBAR,G CHUTNEY', 'CHANNA MASALA, RAITHA, PICKLE');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('BBJ, SPROUTS*', 'BBJ, SPROUTS*', 'BBJ, SPROUTS*', 'BBJ, SPROUTS*', 'BBJ, SPROUTS*', 'BBJ,SPROUTS*', 'BBJ, SPROUTS*');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SEASONAL CUT FRUITS***', 'BANANA (1)', 'FRUIT***', 'BANANA (1)', 'FRUIT***', 'Ban ana(1)', 'FRUIT***');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT', 'TEA, COFFEE, MILK, SUGAR, SALT');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PULKHA , DAL MAKHANI', 'TAWA CHAPATHI, DUM ALOO', 'PULKHA , PANCHRATAN DAL', 'TAWA CHAPATHI , CHANNA MASALA', 'PULKHA ,RAJMA DAL,', 'TAWA CHAPATHI, GREEN PEAS KURMA', 'None');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PANEER BUTTER MASALA / KAJU CURRY', 'BHINDI FRY', 'BEANS CARROT PORIYAL', 'ONION PAKODA***, PERUGU PACHADI', 'KADAI PANNER', 'JEERA RICE,BEETROOT PORIYAL', 'LAUKI CHANA DAL, GOBI 65***');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('VEG BIRYANI , ONION RAITHA,Tawa chapatti', 'RICE,SAMBAR,RASAM, CURD', 'CURD,FRYUMS', 'RICE,MASALA SAMBAR, CURD,FRYUMS', 'RICE, RASAM, CURD,PAPAD', 'RICE,RASAM, CURD,FRY UMS', 'None');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('BADUSHA', 'Gongum PICKLE ,PAPAD', 'Mix veg PICKIE', 'Tomato PICKLE', 'Mango PICKLE', 'Lime PICKLE', 'None');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('LEMON JUICE', 'SUGAR ,SALT ,GHEE, PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR ,SALT,GHEE, PODI', 'SUGAR ,SALT ,GHEE,PODI', 'SUGAR ,SALT ,GHEE,PODI');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SAIAD', 'MUSKMELON JUICE', 'SALAD', 'BANANA JUICE', 'SALAD', 'SEASONAL FRUIT JUICE', 'None');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('PANI PURI', 'PASTA', 'Aloo Bonda, SAUCE', 'BOILED GROUNDNUTS', 'SWEET CORN (half piece-6cm)', 'ONION PAKODA', 'None');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('TEA, COFEE,MILK,SUGAR', 'TEA,COFEE, MILK,SUGAR', 'TEA,COFEE, MILK,SUGAR', 'TEA, COFEE, MILK, SUGAR', 'TEA,COFEE,MILK,SUGAR', 'TEA,COFEE, MILK,SUGAR', 'TEA,COFEE,MILK, SUGAR');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('CHAPATTI , ALOO MATTAR', 'CHOLE BATURE, ONION MIRCH SALAD', 'KAL DOSA,TOMATO CHUTNEY', 'PHUIKA, VEG BIRYANI , RAITHA', 'LACHA PARATHA ,SALNA', 'PHUIKA , Veg Pulao, RAITHA', 'PULKA, Chitinnd Paneer');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('Tamarind Rice, BUTTERMILK,FRYUMS', 'WHITE RICE, SNAKE GOURD KOOTU', 'RICE,SAMBAR', 'PANEER MANCHURIAN/gobi MANCHURIAN', 'VEG PORYAL,RICE, RASAM', 'KAJU CURRY', 'BAGARA RICE, BUTTERMIIK');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('Lime PICKLE,GHEE', 'BUTTER MILK, RASAM', 'PAPAD, BUTTERMILK', 'DAL FRY', 'ONION SALAD', 'KesariBat h,RASAM', 'VERMICELLI PAYASAM');
INSERT INTO Screenshot_2025_04_14_010739 (SUNDAY, MONDAY, TUESDAY, WEDN_ESDAY, THURSDAY, FRIDAY, SATURDAY) VALUES ('SEASONAL CUT FRUITS', 'BANANA', 'GULAB JAMUN(2)', 'KHEER', 'BADAM MILK HOT', 'None', 'None');
